# fly.toml app configuration file generated for jobboard-staging on 2025-07-25T11:52:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobboard-staging'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]
  platform = 'amd64'

  [build.args]
    RAILS_HOST = "0.0.0.0"
    PORT = "8080"

[env]
  DATABASE_URL = 'sqlite3:///data/staging.sqlite3'
  RAILS_HOST = "0.0.0.0"
  PORT = '8080'
  SOLID_QUEUE_IN_PUMA = 'true'
  RAILS_ASSET_HOST = 'https://jobboard-staging.fly.dev/'
  STAGING_ENV="true"
  RAILS_WEB_URL="https://jobboard-staging.fly.dev"
  EMAIL_SENDER_ADDRESS='staging.noreply@drillcrew.work'

[[mounts]]
  source = 'data_stg_2'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = '10s'
  timeout = '2s'
  grace_period = '5s'
  method = 'GET'
  path = '/up'
  protocol = 'http'
  tls_skip_verify = false

[http_service.checks.headers]
  X-Forwarded-Proto = 'https'

[[vm]]
  memory_mb = 2048
  cpu_kind = "shared"
  cpus = 2
