# fly.toml app configuration file generated for jobboard-production on 2025-09-12T12:11:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobboard-production'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]
  platform = 'amd64'

  [build.args]
    RAILS_HOST = "0.0.0.0"
    PORT = "8080"

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'
  EMAIL_SENDER_ADDRESS = 'noreply@drillcrew.work'
  PORT = '8080'
  RAILS_ASSET_HOST = 'https://drillcrew.work'
  RAILS_HOST = '0.0.0.0'
  RAILS_WEB_URL = 'https://drillcrew.work'
  SOLID_QUEUE_IN_PUMA = 'true'
  BLAZER_DATABASE_URL_MAIN='sqlite3:storage/production.sqlite3'
  BLAZER_DATABASE_URL_ANALYTICS='sqlite3:storage/production_analytics.sqlite3'

[[mounts]]
  source = 'production_data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory_mb = 2048
  cpu_kind = "shared"
  cpus = 2