# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
primary: &primary
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  extensions:
    - <%= SqliteUlid.ulid_loadable_path %>

analytics: &analytics
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  migrations_paths: db/analytics_migrate


development:
  primary:
    <<: *primary
    database: storage/development.sqlite3
  analytics:
    <<: *analytics
    database: storage/development_analytics.sqlite3
  queue:
    <<: *primary
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *primary
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *primary
    database: storage/test.sqlite3
  analytics:
    <<: *analytics
    database: storage/test_analytics.sqlite3
  queue:
    <<: *primary
    database: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary
    database: storage/test_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *primary
    database: storage/test_cache.sqlite3
    migrations_paths: db/cache_migrate



# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *primary
    database: storage/production.sqlite3
    url: <%= ENV["DATABASE_URL"] %>
  analytics:
    <<: *analytics
    database: storage/production_analytics.sqlite3
    url: <%= ENV["DATABASE_URL"] ? ENV["DATABASE_URL"].sub(/\.sqlite3$/, "_analytics.sqlite3") : nil %>
  cache:
    <<: *primary
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
    url: <%= ENV["DATABASE_URL"] ? ENV["DATABASE_URL"].sub(/\.sqlite3$/, "_cache.sqlite3") : nil %>
  queue:
    <<: *primary
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
    url: <%= ENV["DATABASE_URL"] ? ENV["DATABASE_URL"].sub(/\.sqlite3$/, "_queue.sqlite3") : nil %>
  cable:
    <<: *primary
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
    url: <%= ENV["DATABASE_URL"] ? ENV["DATABASE_URL"].sub(/\.sqlite3$/, "_cable.sqlite3") : nil %>
